public enum ClaseLexica {
    VAR, ENT, REAL, BOOL, TRUE, FALSE, AND, NOT, OR, 
    PAP, PCIERRE, ARROBA, AMPERSAND, PUNTOYCOMA, LLAVEA, LLAVEC,
    MAS, MENOS, POR, DIV, MAYOR, MENOR, MAYORIG, MENORIG, IGUAL, DESIGUAL, ASIG, EOF,
}