
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Mar 06 11:10:37 CET 2024
//----------------------------------------------------

package c_ast_ascendente;


/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PUNTOYCOMA = 20;
  public static final int CIRCUNFLEJO = 22;
  public static final int RESTA = 7;
  public static final int CORCHETEC = 25;
  public static final int CORCHETEA = 24;
  public static final int INT = 31;
  public static final int LITEREAL = 4;
  public static final int WRITE = 44;
  public static final int DELETE = 42;
  public static final int AMPERSAND2 = 30;
  public static final int NOT = 51;
  public static final int AND = 50;
  public static final int IDENTIFICADOR = 2;
  public static final int MENORIGUAL = 14;
  public static final int IGUAL = 15;
  public static final int TYPE = 46;
  public static final int OR = 52;
  public static final int BOOL = 33;
  public static final int CALL = 47;
  public static final int ARROBA = 28;
  public static final int DIV = 9;
  public static final int SUMA = 6;
  public static final int IF = 37;
  public static final int LITENTERO = 3;
  public static final int AMPERSAND = 29;
  public static final int MAYORIGUAL = 13;
  public static final int EOF = 0;
  public static final int ASIG = 17;
  public static final int TRUE = 48;
  public static final int NEW = 41;
  public static final int error = 1;
  public static final int MUL = 8;
  public static final int COMA = 21;
  public static final int NULL = 35;
  public static final int MENOR = 12;
  public static final int MOD = 10;
  public static final int DESIGUAL = 16;
  public static final int REAL = 32;
  public static final int MAYOR = 11;
  public static final int ELSE = 38;
  public static final int PUNTO = 23;
  public static final int NL = 45;
  public static final int READ = 43;
  public static final int WHILE = 39;
  public static final int PARC = 19;
  public static final int PROC = 36;
  public static final int STRING = 34;
  public static final int LITCADENA = 5;
  public static final int PARA = 18;
  public static final int FALSE = 49;
  public static final int STRUCT = 40;
  public static final int LLAVEC = 27;
  public static final int LLAVEA = 26;
}

