
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Apr 11 20:59:20 CEST 2024
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PUNTOYCOMA = 16;
  public static final int CIRCUNFLEJO = 18;
  public static final int RESTA = 3;
  public static final int CORCHETEC = 21;
  public static final int CORCHETEA = 20;
  public static final int INT = 27;
  public static final int WRITE = 40;
  public static final int DELETE = 38;
  public static final int AMPERSAND2 = 26;
  public static final int IDENTIFICADOR = 49;
  public static final int NOT = 47;
  public static final int AND = 46;
  public static final int MENORIGUAL = 10;
  public static final int IGUAL = 11;
  public static final int TYPE = 42;
  public static final int OR = 48;
  public static final int BOOL = 29;
  public static final int CALL = 43;
  public static final int ARROBA = 24;
  public static final int DIV = 5;
  public static final int SUMA = 2;
  public static final int IF = 33;
  public static final int LITENTERO = 50;
  public static final int AMPERSAND = 25;
  public static final int MAYORIGUAL = 9;
  public static final int EOF = 0;
  public static final int ASIG = 13;
  public static final int TRUE = 44;
  public static final int LITREAL = 51;
  public static final int NEW = 37;
  public static final int error = 1;
  public static final int MUL = 4;
  public static final int COMA = 17;
  public static final int NULL = 31;
  public static final int MENOR = 8;
  public static final int MOD = 6;
  public static final int DESIGUAL = 12;
  public static final int REAL = 28;
  public static final int MAYOR = 7;
  public static final int ELSE = 34;
  public static final int PUNTO = 19;
  public static final int NL = 41;
  public static final int READ = 39;
  public static final int WHILE = 35;
  public static final int PARC = 15;
  public static final int LITCADENA = 52;
  public static final int PROC = 32;
  public static final int STRING = 30;
  public static final int PARA = 14;
  public static final int FALSE = 45;
  public static final int STRUCT = 36;
  public static final int LLAVEC = 23;
  public static final int LLAVEA = 22;
}

